# Generated by Django 3.1.7 on 2021-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_carpet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='image',
            field=models.FilePathField(path='images'),
        ),
    ]
