# Generated by Django 3.1.7 on 2021-04-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20210408_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='image',
        ),
    ]
