# Generated by Django 3.1.7 on 2021-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_carpet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
