# Generated by Django 3.1.7 on 2021-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_carpet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='material',
            field=models.CharField(choices=[('W', 'wol'), ('Z', 'zijde'), ('K', 'kunststof')], max_length=50),
        ),
    ]
