# Generated by Django 3.1.7 on 2021-04-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20210408_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='material',
            field=models.CharField(choices=[('Wol', 'wol'), ('Zijde', 'zijde'), ('kunststof', 'kunststof')], max_length=50),
        ),
    ]
