# Generated by Django 3.1.7 on 2021-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20210413_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='material',
            field=models.CharField(choices=[('Wol', 'wol'), ('Zijde', 'zijde'), ('Kunststof', 'kunststof')], max_length=50),
        ),
    ]
